steps:
  # Build Next.js Frontend
  - name: 'node:20'
    id: 'install-frontend-deps'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:20'
    id: 'build-frontend'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'

  # Install Python dependencies for RAG Backend
  - name: 'python:3.11'
    id: 'install-backend-deps'
    dir: 'RAG'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt', 'fastapi', 'uvicorn']

  # Install Python dependencies for Sentiment Backend
  - name: 'python:3.11'
    id: 'install-sentiment-deps'
    dir: 'sentiment'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt', 'fastapi', 'uvicorn']

  # Optional: Run tests if you have them
  # - name: 'python:3.11'
  #   id: 'test-backend'
  #   dir: 'RAG'
  #   entrypoint: 'pytest'
  #   args: ['-v']

  # Optional: Lint frontend
  # - name: 'node:20'
  #   id: 'lint-frontend'
  #   dir: 'frontend'
  #   entrypoint: 'npm'
  #   args: ['run', 'lint']

  # Build Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_BACKEND}:${SHORT_SHA}'
      - '-f'
      - 'RAG/Dockerfile'
      - 'RAG'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-image'
    args:
      - 'push'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_BACKEND}:${SHORT_SHA}'

  # Deploy Backend (FastAPI) to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME_BACKEND}'
      - '--image'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_BACKEND}:${SHORT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_KEY=supabase-key:latest,ASSEMBLYAI_KEY=assemblyai-key:latest,HF_TOKEN=hf-token:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
    env:
      - 'CLOUDSDK_RUN_PLATFORM=managed'

  # Build Sentiment Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-sentiment-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_SENTIMENT}:${SHORT_SHA}'
      - '-f'
      - 'sentiment/Dockerfile'
      - 'sentiment'

  # Push Sentiment Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sentiment-image'
    args:
      - 'push'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_SENTIMENT}:${SHORT_SHA}'

  # Deploy Sentiment API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-sentiment'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME_SENTIMENT}'
      - '--image'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_SENTIMENT}:${SHORT_SHA}'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-secrets'
      - 'SUPABASE_URL=supabase-url:latest,SUPABASE_KEY=supabase-key:latest,ASSEMBLYAI_KEY=assemblyai-key:latest,HF_TOKEN=hf-token:latest'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
    env:
      - 'CLOUDSDK_RUN_PLATFORM=managed'

  # Get Backend URLs for frontend configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-backend-urls'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe ${_SERVICE_NAME_BACKEND} --region=${_REGION} --format='value(status.url)')
        SENTIMENT_URL=$(gcloud run services describe ${_SERVICE_NAME_SENTIMENT} --region=${_REGION} --format='value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        echo "Sentiment URL: $SENTIMENT_URL"
        echo "BACKEND_URL=$BACKEND_URL" >> /workspace/backend-url.env
        echo "SENTIMENT_URL=$SENTIMENT_URL" >> /workspace/backend-url.env
    env:
      - 'CLOUDSDK_RUN_PLATFORM=managed'

  # Build Frontend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_FRONTEND}:${SHORT_SHA}'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend'

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-image'
    args:
      - 'push'
      - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_FRONTEND}:${SHORT_SHA}'

  # Deploy Frontend (Next.js) to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe ${_SERVICE_NAME_BACKEND} --region=${_REGION} --format='value(status.url)')
        SENTIMENT_URL=$(gcloud run services describe ${_SERVICE_NAME_SENTIMENT} --region=${_REGION} --format='value(status.url)')
        gcloud run deploy ${_SERVICE_NAME_FRONTEND} \
          --image=gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_FRONTEND}:${SHORT_SHA} \
          --platform=managed \
          --region=${_REGION} \
          --allow-unauthenticated \
          --port=3000 \
          --set-env-vars="NODE_ENV=production,NEXT_PUBLIC_API_URL=$BACKEND_URL,NEXT_PUBLIC_SENTIMENT_API_URL=$SENTIMENT_URL" \
          --memory=1Gi \
          --cpu=2 \
          --timeout=300 \
          --max-instances=10
    env:
      - 'CLOUDSDK_RUN_PLATFORM=managed'

# Substitutions for environment variables
substitutions:
  _PROJECT_ID: 'simpliearn-452813'
  _REGION: 'us-central1'
  _SERVICE_NAME_FRONTEND: 'simpli-earn-frontend'
  _SERVICE_NAME_BACKEND: 'simpli-earn-backend'
  _SERVICE_NAME_SENTIMENT: 'simpli-earn-sentiment'

# Timeout for the entire build
timeout: '1800s'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Available images (for reference if using Docker builds)
# images:
#   - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_FRONTEND}:${SHORT_SHA}'
#   - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME_BACKEND}:${SHORT_SHA}'

